name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: false

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Delete tag and GitHub release if linter or tests fail
        if: failure()
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          RELEASE_ID=$(gh release list --tag $TAG --json id --jq '.[0].id')
          if [ -n "$RELEASE_ID" ]; then gh release delete $RELEASE_ID --yes; fi
          git push --delete origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in package.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin main
          git pull --ff-only origin main
          git checkout main
          git add package.json
          git commit -m "chore: update version to ${VERSION}"
          git push origin main

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
